// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC560q-RlsCgFbB_r6hRPmpJRpUiKEKp6U',
    appId: '1:442654998013:web:b27ecbeebe7176bdeeed94',
    messagingSenderId: '442654998013',
    projectId: 'fresh-fruity-1e7c0',
    authDomain: 'fresh-fruity-1e7c0.firebaseapp.com',
    storageBucket: 'fresh-fruity-1e7c0.firebasestorage.app',
    measurementId: 'G-MB9KMYK3KN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBT8QHTJ20Nrnm3YUMMXap47yjaJXhn8AQ',
    appId: '1:442654998013:android:3569e42cbf603ab5eeed94',
    messagingSenderId: '442654998013',
    projectId: 'fresh-fruity-1e7c0',
    storageBucket: 'fresh-fruity-1e7c0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVclGtQvYW9dIvcQ6xcY5VEs0eUuMks4U',
    appId: '1:442654998013:ios:7ef6c381bde069fbeeed94',
    messagingSenderId: '442654998013',
    projectId: 'fresh-fruity-1e7c0',
    storageBucket: 'fresh-fruity-1e7c0.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBVclGtQvYW9dIvcQ6xcY5VEs0eUuMks4U',
    appId: '1:442654998013:ios:7ef6c381bde069fbeeed94',
    messagingSenderId: '442654998013',
    projectId: 'fresh-fruity-1e7c0',
    storageBucket: 'fresh-fruity-1e7c0.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC560q-RlsCgFbB_r6hRPmpJRpUiKEKp6U',
    appId: '1:442654998013:web:f3972222d1ade18ceeed94',
    messagingSenderId: '442654998013',
    projectId: 'fresh-fruity-1e7c0',
    authDomain: 'fresh-fruity-1e7c0.firebaseapp.com',
    storageBucket: 'fresh-fruity-1e7c0.firebasestorage.app',
    measurementId: 'G-C8SRZ9J9E5',
  );
}
